### ISSUE TITLE
document for ansible provider

### ISSUE THREAD

**Issue by gyliu513** [cloud-pak-gitops/crossplane-provider-ansible#2]
### What happened?

We need to update the document to enable someone can do some test.

@morningspace @fahedouch 

### What environment did it happen in?
Crossplane version:

**Comment by fahedouch** [comment]
hello @gyliu513 ,

thank you for raising this. I embedded some use case example in this PR https://github.com/cloud-pak-gitops/crossplane-provider-ansible/pull/3/files, but I agree with you we need a clear documentation

**Comment by fahedouch** [comment]
Closed for https://github.com/cloud-pak-gitops/crossplane-provider-ansible/pull/5
